version: "3.9"

services:
  app:
    build:
      # use the current directory as context
      context: .
      args:
        - DEV=true
      # expose 8000 on local to 8000 to docker container
    ports:
      - "8000:8000"
      # /app in our pc to /app on docker container - to avoid recreating the image
    volumes:
      - ./app:/app
      # Command to run the service - by default uses the command on the Dockerfile
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      # db as the db service
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    # Set initial db configuration
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme

volumes:
  # Name of volume - Docker will create this for us
  dev-db-data: